// 007 Arcade runtime. No network calls: GitHub Pages can run this entirely client-side.
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='g007_arcade_v3';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{name:'007',score:10000,xp:0,level:1,missions:0,history:[],sound:true};
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()};
const fmt=n=>Math.max(0,Math.floor(n)).toLocaleString('de-DE');
let audioCtx=null;
function beep(f=440,d=.08,type='sine'){if(!state.sound)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.045,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d+.02)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2200)}
function addXP(n){state.xp+=n;while(state.xp>=100){state.xp-=100;state.level++;toast('LEVEL UP — '+state.level);beep(980,.12)}state.missions++;save()}
function log(t,good=true){state.history.unshift({t,good});state.history=state.history.slice(0,10)}
function render(){if(!$('#coins'))return;$('#coins').textContent=fmt(state.score);$('#agentName').textContent=state.name;$('#heroName').textContent=state.name;$('#level').textContent=state.level;$('#xp').textContent=state.xp;$('#missionProgress').style.width=((state.missions%5)*20)+'%';$('#missionText').textContent=(state.missions%5)+' / 5 missions';$('#history').innerHTML=state.history.length?state.history.slice(0,8).map(x=>`<span class="result-pill ${x.good?'win':'loss'}">${x.t}</span>`).join(''):'<span>NO MISSIONS YET</span>'}
function openGame(type){$('#modal').classList.remove('hidden');const c=$('#modalContent');({reflex:reflexUI,wheel:wheelUI,memory:memoryUI,dice:diceUI,sequence:sequenceUI,target:targetUI}[type]||reflexUI)(c)}
const head=(a,b)=>`<h2 class="modal-title">${a}</h2><p class="modal-sub">${b}</p>`;
function done(text,xp=20){log(text,true);addXP(xp);beep(820,.08);toast(text)}
function reflexUI(c){let code=[0,0,0].map(()=>Math.floor(Math.random()*10)).join('');c.innerHTML=head('CODE BREAKER','Memorize the 3-digit code and enter it as quickly as possible.')+`<div class="code-display">${code}</div><div class="game-controls"><input id="codeInput" class="text-input" inputmode="numeric" maxlength="3" placeholder="3 digits"><button class="action" id="checkCode">CHECK</button></div><p class="modal-sub" id="codeMsg">ACCESS TIMER RUNNING…</p>`;const started=performance.now();$('#codeInput').focus();$('#checkCode').onclick=()=>{if($('#codeInput').value.trim()===code){const t=((performance.now()-started)/1000).toFixed(2);done('CODE '+t+'s',30);$('#codeMsg').textContent='ACCESS GRANTED — '+t+'s'}else{log('CODE MISS',false);state.score=Math.max(0,state.score-50);save();$('#codeMsg').textContent='ACCESS DENIED';beep(150,.1,'square')}}}
function wheelUI(c){c.innerHTML=head('PRECISION WHEEL','Stop the moving marker inside the cyan target sector.')+`<div class="precision"><div class="precision-ring"></div><div class="precision-zone"></div><div class="needle" id="needle"></div></div><button class="action" id="lockWheel">LOCK TARGET</button><p class="modal-sub" id="wheelMsg">TRACKING…</p>`;let deg=0,running=true,n=$('#needle');function tick(){if(!running)return;deg=(deg+4)%360;n.style.transform=`rotate(${deg}deg)`;requestAnimationFrame(tick)}tick();$('#lockWheel').onclick=()=>{running=false;const d=Math.min(deg,360-deg);if(d<24||Math.abs(deg-180)<24){done('PRECISION HIT +250',28);$('#wheelMsg').textContent='PERFECT LOCK'}else{log('PRECISION MISS',false);state.score=Math.max(0,state.score-35);save();$('#wheelMsg').textContent='MISS — RECALIBRATE';beep(150,.1,'square')}}}
function memoryUI(c){c.innerHTML=head('GRID OPS','Memorize the highlighted signal and repeat it.')+`<div class="memory-grid">${Array.from({length:9},(_,i)=>`<button class="memory-cell" data-i="${i}">◈</button>`).join('')}</div><button class="action" id="memoryStart">START SCAN</button><p class="modal-sub" id="memoryMsg">Awaiting scan.</p>`;const cells=$$('.memory-cell');let seq=[],pos=0,locked=true;const flash=async()=>{locked=true;for(const i of seq){cells[i].classList.add('revealed');await new Promise(r=>setTimeout(r,360));cells[i].classList.remove('revealed');await new Promise(r=>setTimeout(r,120))}pos=0;locked=false;$('#memoryMsg').textContent='REPEAT SIGNAL'};$('#memoryStart').onclick=()=>{seq.push(Math.floor(Math.random()*9));flash()};cells.forEach(cell=>cell.onclick=()=>{if(locked)return;const i=+cell.dataset.i;if(i!==seq[pos]){locked=true;log('GRID FAIL',false);state.score=Math.max(0,state.score-40);save();$('#memoryMsg').textContent='SIGNAL LOST';beep(150,.1,'square');return}cell.classList.add('revealed');setTimeout(()=>cell.classList.remove('revealed'),160);pos++;if(pos===seq.length){locked=true;done('GRID CLEAR ×'+seq.length,25+seq.length*4);$('#memoryMsg').textContent='SIGNAL ACQUIRED — NEXT LEVEL'}})}
function diceUI(c){let target=Math.floor(Math.random()*9)+1;c.innerHTML=head('DICE REACTION','Hit the current target number.')+`<div class="dice-result" id="diceValue">${target}</div><button class="action" id="rollDice">ROLL</button><p class="modal-sub" id="diceMsg">Target locked.</p>`;$('#rollDice').onclick=()=>{const n=Math.floor(Math.random()*9)+1;$('#diceValue').animate([{transform:'rotateX(0)'},{transform:'rotateX(540deg)'},{transform:'rotateX(720deg)'}],{duration:340});setTimeout(()=>{$('#diceValue').textContent=n;if(n===target){done('DICE HIT +150',24);target=Math.floor(Math.random()*9)+1;$('#diceMsg').textContent='NEW TARGET'}else{log('DICE MISS',false);state.score=Math.max(0,state.score-15);save();$('#diceMsg').textContent='MISS — '+n+' / '+target;beep(140,.08,'square')}},170)}}
function sequenceUI(c){c.innerHTML=head('SEQUENCE 007','Remember the glowing pattern. Every successful round adds a step.')+`<div class="sequence-grid">${Array.from({length:16},(_,i)=>`<button class="sequence-cell" data-i="${i}"></button>`).join('')}</div><button class="action" id="sequenceStart">START</button><p class="modal-sub" id="sequenceMsg">Ready.</p>`;const cells=$$('.sequence-cell');let seq=[],input=[],locked=true;async function show(){locked=true;for(const i of seq){cells[i].classList.add('revealed');await new Promise(r=>setTimeout(r,280));cells[i].classList.remove('revealed');await new Promise(r=>setTimeout(r,100))}input=[];locked=false;$('#sequenceMsg').textContent='REPEAT'}$('#sequenceStart').onclick=()=>{seq.push(Math.floor(Math.random()*16));show()};cells.forEach(x=>x.onclick=()=>{if(locked)return;const i=+x.dataset.i;x.classList.add('revealed');setTimeout(()=>x.classList.remove('revealed'),110);input.push(i);if(input[input.length-1]!==seq[input.length-1]){locked=true;log('SEQUENCE FAIL',false);state.score=Math.max(0,state.score-50);save();$('#sequenceMsg').textContent='PATTERN LOST';return}if(input.length===seq.length){locked=true;done('SEQUENCE ×'+seq.length,20+seq.length*4);$('#sequenceMsg').textContent='MATCH — NEXT ROUND'}})}
function targetUI(c){c.innerHTML=head('TARGET LOCK','Click the moving core. Pure reflex challenge.')+`<div class="target-zone" id="targetZone"><button class="target-core" id="targetCore">+</button></div><p class="modal-sub">CORE ARMED.</p>`;const z=$('#targetZone'),core=$('#targetCore');function move(){const x=Math.max(6,Math.random()*(z.clientWidth-58)),y=Math.max(6,Math.random()*(z.clientHeight-58));core.style.left=x+'px';core.style.top=y+'px'}move();let total=0;core.onclick=()=>{total+=100;done('TARGET +'+total,16);move()}}
function profile(){const c=$('#modalContent');$('#modal').classList.remove('hidden');c.innerHTML=head('AGENT PROFILE','Nickname and local access code.')+`<div class="game-controls"><input id="nameInput" class="text-input" maxlength="14" value="${state.name}"><button class="action" id="saveProfile">SAVE</button></div><p class="modal-sub">LOCAL CODE: <b style="color:var(--gold2)">G007-${String((state.name.length*731)%10000).padStart(4,'0')}</b></p>`;$('#saveProfile').onclick=()=>{state.name=$('#nameInput').value.trim()||'007';save();close();toast('PROFILE UPDATED');beep(700)}}
function close(){$('#modal').classList.add('hidden')}
function injectStyles(){const s=document.createElement('style');s.textContent=`.text-input{flex:1;min-width:180px;padding:12px;border-radius:10px;background:#0d1620;border:1px solid #2a3d50;color:#fff;outline:0}.text-input:focus{border-color:#35d9ff;box-shadow:0 0 0 3px #35d9ff14}.code-display{text-align:center;font:900 64px Orbitron;letter-spacing:14px;color:var(--gold2);text-shadow:0 0 30px #d8b15a55;margin:28px 0}.precision{width:260px;height:260px;margin:24px auto;position:relative;border-radius:50%;border:2px solid #263b4e;box-shadow:0 0 45px #35d9ff18}.precision-ring{position:absolute;inset:18px;border-radius:50%;border:1px solid #35d9ff44;background:repeating-radial-gradient(circle,#ffffff00 0 30px,#35d9ff12 31px 32px)}.precision-zone{position:absolute;inset:6px;border-radius:50%;background:conic-gradient(from 0deg,#35d9ff00 0 42deg,#35d9ff55 43deg 70deg,#35d9ff00 71deg 360deg);filter:drop-shadow(0 0 15px #35d9ff88)}.needle{position:absolute;left:50%;top:18px;width:2px;height:112px;background:var(--gold2);transform-origin:50% 112px;box-shadow:0 0 16px #ffe39a}.memory-grid,.sequence-grid{max-width:430px;margin:22px auto;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.sequence-grid{grid-template-columns:repeat(4,1fr)}.memory-cell,.sequence-cell{aspect-ratio:1;border-radius:10px;background:#111c28;border:1px solid #2a4054;color:#6d8194;transition:.14s}.memory-cell.revealed,.sequence-cell.revealed{background:#15352f;border-color:#43e69b;box-shadow:0 0 24px #43e69b44;transform:scale(.96)}.target-zone{height:330px;margin-top:20px;border:1px solid #24384a;border-radius:18px;background:radial-gradient(circle at 50% 50%,#142a38,#070c12 70%);position:relative;overflow:hidden}.target-zone:after{content:'';position:absolute;inset:12%;border:1px dashed #35d9ff30;border-radius:50%;animation:spin 9s linear infinite}.target-core{position:absolute;z-index:2;width:50px;height:50px;border-radius:50%;border:1px solid #ffe39a;background:#13212c;color:#ffe39a;font:900 24px Orbitron;box-shadow:0 0 30px #ffe39a55;transition:.12s}.target-core:hover{transform:scale(1.14)}.modal-box{animation:modalIn .28s cubic-bezier(.2,.9,.2,1)}@keyframes modalIn{from{transform:translateY(18px) scale(.96);opacity:0}to{transform:none;opacity:1}}`;document.head.appendChild(s)}
$('#closeModal').onclick=close;$('#modal').onclick=e=>{if(e.target.id==='modal')close()};$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$('#profileBtn').onclick=profile;$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'🔊':'🔇';if(state.sound)beep(700)};$('#missionsBtn').onclick=()=>toast('MISSION: COMPLETE 5 SKILL CHALLENGES');
const events=['NIGHT OPS — LIVE','SIGNAL HUNT — ACTIVE','AGENT RUSH — ACTIVE','NETWORK PULSE — LIVE'];let ei=0;setInterval(()=>$('#eventText').textContent=events[ei++%events.length],6500);
const preview=document.querySelector('.mine-grid');if(preview){preview.innerHTML=Array.from({length:25},()=>'<i></i>').join('')}
injectStyles();render();